services:
  bitcoind:
    build:
      context: ./bitcoind
    container_name: bitcoind
    volumes:
      - bitcoind_data:/data
    ports:
      - "8332:8332" # JSON-RPC port
      - "8333:8333" # P2P port
    environment:
      BITCOIND_RPC_USER: "user"
      BITCOIND_RPC_PASSWORD: "password"
      BITCOIND_RPC_ALLOWIP: "0.0.0.0/0"
    hostname: bitcoind
    command: >
      bitcoind
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=${BITCOIND_RPC_USER}
      -rpcpassword=${BITCOIND_RPC_PASSWORD}
      -datadir=/data
      -txindex=1
      -printtoconsole=1

  ckpool:
    build:
      context: ./ckpool
    container_name: ckpool
    ports:
      - "3333:3333" # Stratum port
    depends_on:
      - bitcoind
    environment:
      CKPOOL_RPC_HOST: "bitcoind"
      CKPOOL_RPC_USER: "user"
      CKPOOL_RPC_PASSWORD: "password"
    hostname: ckpool
    command: >
      /bin/bash -c "
      ckpool
      -L
      -c ckpool.conf
      "

volumes:
  bitcoind_data:
